dist: xenial

language: rust

rust:
  - nightly

cache: cargo

# Packages for Coveralls.io
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

script:
  - make test

after_success:
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make
  - sudo make install && cd ../..
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/storaget-*