
dist: xenial

language: rust

rust:
  - nightly

addons:
  apt:
    packages:
      - libssl-dev

cache: cargo

before_cache: |
  cargo install cargo-tarpaulin -f

script:
  - make test

after_success:
  - cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID