
dist: xenial

language: rust

rust:
  - nightly

cache: cargo

# Packages for Coveralls.io
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

script:
  - make test

after_success:
  - cargo install --force cargo-travis
  - export PATH=$HOME/.cargo/bin:$PATH
  - rustup component add rustfmt-preview
  - cargo coveralls